version: '3.9'

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfolio
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - "5432:5432"

  backend:
    build: ./server
    restart: always
    environment:
      JWT_SECRET: sjahdjasa2312shdjashiuxzc
      REFRESH_SECRET: sadasdasdasd132sad131a
      ACCESS_TOKEN_EXPIRES_IN: 15m
      REFRESH_TOKEN_EXPIRES_IN: 7d
      DB_USER: postgres
      DB_HOST: db
      DB_NAME: portfolio
      DB_PASSWORD: postgres
      DB_PORT: 5432
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./react
    environment:
      BACK_PORT: 5000
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: